from __future__ import annotations

import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET


SRC = Path("/Users/lucindaliu/Downloads/business plan -绿色经济采信基础设施04-20.pptx")
OUT = Path("/Users/lucindaliu/Downloads/lucinda-climateseal-0916new-main/business-plan-green-trust-infrastructure-EN.pptx")

NS_A = "http://schemas.openxmlformats.org/drawingml/2006/main"
ET.register_namespace("a", NS_A)


T = {
    "绿色经济「采信」基础设施": "Green Economy Trust Infrastructure",
    "帮“企业": "Helps enterprises,",
    "产品": "products",
    "金融资产”证明是否绿色": "and financial assets prove they are green",
    "通过市场和监管验收，构建绿色领域": "Accepted by markets and regulators; building the green-economy trust layer",
    "市场不缺资产，而是": "The market does not lack assets, but",
    "资产被“采信难”锁死": "assets are locked by the trust-acceptance bottleneck",
    "真正卡住流通的是采信难": "The real circulation blocker is trust acceptance",
    "证明难": "Hard to prove",
    "验收难": "Hard to accept",
    "绿色经济": "Green economy",
    "采信阀门": "Trust gate",
    "多": "more",
    "释放": "release",
    "流通池": "circulation pool",
    "亿吨库存": "100M tons in inventory",
    "碳资产": "carbon assets",
    "万供应链企业": "10K+ supply-chain firms",
    "亿批次产品": "100M product batches",
    "合规市场": "compliance market",
    "绿色金融": "green finance",
    "贷款": "loans",
    "债券": "bonds",
    "买家交易采信": "buyer transaction trust",
    "年": "year",
    "年度合规采信花费": "annual compliance trust spend",
    "亿": "100M",
    "通过": "pass",
    "采信": "trusted acceptance",
    "瓶颈：采信（绿色证明": "Bottleneck: trust acceptance (green proof",
    "验收": "acceptance",
    "根因：证明太贵、验证太贵、两方口径差异大": "Root cause: proof is costly, verification is costly, and both sides use different criteria",
    "不是主体不绿": "The entities are not necessarily ungreen",
    "而是让绿色证明被市场和监管接受太贵、口径乱": "but making green proof accepted by markets and regulators is too costly and inconsistent",
    "提交方：企业": "Submitters: enterprises",
    "资产开发方": "asset developers",
    "贷款方": "borrowers",
    "验收方：品牌方海关": "Acceptors: brands, customs",
    "资产买方": "asset buyers",
    "银行": "banks",
    "方法学合规": "methodology compliance",
    "证据链合规": "evidence-chain compliance",
    "证明输出": "proof output",
    "个月": "months",
    "个月 ": "months ",
    "合规专家手工": "manual work by compliance experts",
    "周起": "weeks+",
    "风控专家手工 ": "manual work by risk experts ",
    "风控专家手工": "manual work by risk experts",
    "准入规则": "access rules",
    "风险评估": "risk assessment",
    "交割状态": "delivery status",
    "锁住": "locks",
    "资产流通": "asset circulation",
    "口径差异": "criteria gap",
    "绿色证明": "green proof",
    "（合规口径）": "(compliance criteria)",
    "重算重审": "recalculate and re-review",
    "交易": "transaction",
    "融资失败": "financing fails",
    "绿色验收": "green acceptance",
    "（采购": "(procurement",
    "风控口径）": "risk-control criteria)",
    "不同碳场景，本质是同一条决策链的统一市场": "Different carbon scenarios are essentially one market on the same decision chain",
    "同一套“提交方证明→验收方决定→合规": 'One structure: "submitter proves -> acceptor decides -> compliance',
    "资金": "capital",
    "交易流动”的结构 ": 'transaction flow" ',
    "交易流动”的结构": 'transaction flow"',
    "品牌方 审计": "brands / audit",
    "海关": "customs",
    "出口制造 供应链": "export manufacturing / supply chain",
    "碳合规": "carbon compliance",
    "万企业": "10K enterprises",
    "亿批次产品）": "100M product batches)",
    "碳配额": "carbon allowances",
    "万": "10K",
    "企业参与配额）": "enterprises in allowance markets)",
    "万亿美金贷款和债券）": "trillion USD in loans and bonds)",
    "提交方": "submitter",
    "验收方": "acceptor",
    "决定采购订单": "decides purchase orders",
    "税费": "taxes and fees",
    "准入": "access",
    "品牌方  交易所": "brands / exchanges",
    "林业  燃料 航空": "forestry / fuel / aviation",
    "决定交易成败和定价": "decides transaction success and pricing",
    "银行  ": "banks  ",
    "投资": "investors",
    "品牌方   政府": "brands / government",
    "决定融资额度和利率": "decides credit limit and interest rate",
    "付费方": "payer",
    "美金 ": "USD ",
    "美金": "USD",
    "外部咨询机构": "external consulting firms",
    "外部开发机构": "external developers",
    "外部评估机构）": "external assessors)",
    "解决方案": "Solution",
    "把证明和验收": "Turn proof and acceptance",
    "做成一套引擎": "into one engine",
    "两套标准": "two standard modules",
    "护照 ": "passport ",
    "护照": "passport",
    "可复用动态数字证明；闸机 ": "reusable dynamic digital proof; gate ",
    "可复用动态数字证明；闸机": "reusable dynamic digital proof; gate",
    "自动化验收引擎": "automated acceptance engine",
    "数据采集": "data collection",
    "处理": "processing",
    "方法学导航": "methodology navigation",
    "建模": "modeling",
    "核算": "accounting",
    "证据链": "evidence chain",
    "审计": "audit",
    "偏好分析": "preference analysis",
    "融合": "integration",
    "合规": "compliance",
    "资产": "assets",
    "绿金": "green finance",
    "数据整理": "data structuring",
    "方法学": "methodology",
    "合规报告": "compliance report",
    "核验": "verification",
    "流通": "circulation",
    "设计": "design",
    "项目设计": "project design",
    "签发": "issuance",
    "尽调 ": "due diligence ",
    "尽调": "due diligence",
    "风险": "risk",
    "风险凭证": "risk certificate",
    "上架": "listing",
    "放贷": "lending",
    "转手交易 ": "secondary transfer ",
    "转手交易": "secondary transfer",
    "触发条款": "clause trigger",
    "多方法学引擎": "multi-methodology engine",
    "自审计引擎": "self-auditing engine",
    "自审计自动化": "self-auditing automation",
    "引擎 ": "engine ",
    "验收模型": "acceptance model",
    "预制算法": "prebuilt algorithms",
    "交易状态": "transaction status",
    "条款触发": "clause trigger",
    "验收规则前置": "front-loaded acceptance rules",
    "打通口径差异": "bridge criteria gaps",
    "绿色护照": "green passport",
    "验收闸机": "acceptance gate",
    "小时": "hours",
    "周级": "weeks",
    "口径差异大": "large criteria gap",
    "同口径采信": "trusted on the same criteria",
    "绿色证明编译器": "green proof compiler",
    "执行引擎": "execution engine",
    "底层技术": "Core Technology",
    "自审计式自动化": "self-auditing automation",
    "引擎（碳领域": "engine (for carbon)",
    "把咨询": "puts consulting",
    "审计专家装进": "and audit expertise into",
    "流水线": "the workflow",
    "让": "enables",
    "在可审计边界内独立完成合规": "to complete compliance and acceptance independently within auditable boundaries",
    "半黑盒": "semi-black box",
    "难追溯": "hard to trace",
    "手动导航": "manual navigation",
    "手动审计": "manual audit",
    "手动记录": "manual logging",
    "精度差": "low precision",
    "手动方法学导航": "manual methodology navigation",
    "记录": "logging",
    "手动数据处理": "manual data processing",
    "执行链": "execution chain",
    "可信数据链": "trusted data chain",
    "白盒": "white box",
    "高精度": "high precision",
    "审计链": "audit chain",
    "提交方专家组": "submitter expert team",
    "手工慢": "manual and slow",
    "易错": "error-prone",
    "导航": "navigation",
    "数据": "data",
    "评估": "assessment",
    "提交方": "submitter",
    "引擎": "engine",
    "验证方专家组": "verifier expert team",
    "验证方": "verifier",
    "大关卡": "major checkpoints",
    "数据岔口": "data decision forks",
    "追溯": "traceable",
    "自动快": "automated and fast",
    "返工": "rework",
    "打通口径": "align criteria",
    "越用越准": "improves with use",
    "证据": "evidence",
    "编排": "orchestration",
    "合规审计 ": "compliance audit ",
    "合规审计": "compliance audit",
    "资产评估": "asset assessment",
    "金融风控": "financial risk control",
    "方法学模型 ": "methodology models ",
    "方法学模型": "methodology models",
    "自动工作流 ": "automated workflows ",
    "自动工作流": "automated workflows",
    "因子验证 ": "factor validation ",
    "因子验证": "factor validation",
    "基准模型": "baseline models",
    "碳领域高精地图": "high-resolution carbon-domain map",
    "验收算法模型前置": "front-loaded acceptance algorithm models",
    "已验证 ": "validated ",
    "已验证": "validated",
    "合规场景商用": "commercialized in compliance",
    "将上线 ": "launching soon ",
    "将上线": "launching soon",
    "场景": "scenario",
    "已锁定 ": "locked in ",
    "已锁定": "locked in",
    "资产客户": "asset clients",
    "买方": "buyers",
    "高复杂度": "high-complexity",
    "碳足迹项目": "carbon footprint project",
    "法国": "France",
    "重大置信度（最高审计等级）": "material confidence (highest audit level)",
    "组件完成": "module completed",
    "个月上线": "months to launch",
    "家超级买方（中车": "major buyers (CRRC",
    "北汽集团）": "BAIC Group)",
    "资产开发咨询公司（渠道）": "asset-development consulting firms (channels)",
    "万吨碳资产已锁定": "10K tons of carbon assets locked in",
    "个月内进场启动": "months to enter and start",
    "业务进展": "Business Progress",
    "引擎已成功商用": "Engine successfully commercialized",
    "合规场景已验证了": "Compliance scenarios have validated",
    "引擎能力": "engine capability",
    "正基于": "now based on",
    "引擎构建资产开发模块": "the engine to build asset-development modules",
    "合规护照": "compliance passport",
    "资产验证": "asset verification",
    "闸机": "gate",
    "主流资产方法学模型": "mainstream asset methodology models",
    "家客户": "clients",
    "国渠道": "country channels",
    "升级模型": "upgrade model",
    "业务战略": "Business Strategy",
    "合规占领入口": "Use compliance to capture the entry point",
    "再向资产": "then expand into assets",
    "金融延伸": "and finance",
    "从提交方逐步切入验证方流程，在三个场景连续复制": "Enter from submitters, then move into verifier workflows and replicate across three scenarios",
    "自审计自动化引擎（护照": "self-auditing automation engine (passport",
    "闸机） ": "gate) ",
    "闸机）": "gate)",
    "阶段": "Phase",
    "入口": "entry",
    "月）": "mo.)",
    "碳资产升级": "carbon asset upgrade",
    "增长": "growth",
    "渠道：": "Channels:",
    "家碳咨询公司（": "carbon consulting firms (",
    "交付提效": "delivery efficiency +",
    "倍）": "x)",
    "个品牌": "brands",
    "个供应链合规": "supply-chain compliance accounts",
    "裂变": "referrals",
    "渠道": "channels",
    "积压": "backlogged",
    "亿吨待售）": "100M tons for sale)",
    "资产开发商": "asset developers",
    "（低质量资产）": "(low-quality assets)",
    "个开发商": "developers",
    "个资产项目": "asset projects",
    "买方成交": "buyer transactions",
    "利润": "profit",
    "贷款咨询": "loan consulting",
    "绿色贷款": "green loans",
    "合规）": "compliance)",
    "家银行": "banks",
    "个借款方": "borrowers",
    "碳咨询公司": "carbon consulting firms",
    "品牌方": "brands",
    "（购买数字平台）": "(buy digital platform)",
    "推荐": "referral",
    "资产升级": "asset upgrade",
    "认证升级": "certification upgrade",
    "绿色": "green",
    "税抵": "tax credit",
    "护照用量": "passport usage",
    "闸机嵌入量": "gate embedding",
    "咨询公司用": "consultants use",
    "品牌方验证": "brand verification",
    "资产开发商用": "developers use",
    "交易所接入": "exchange access",
    "银行用": "banks use",
    "银行风控接入": "bank risk-control access",
    "当护照用量足够大、闸机嵌入足够深": "When passport usage is large enough and gate embedding is deep enough",
    "两端都依赖同一套轨道，构成采信的基础设施": "both sides depend on the same rails, forming trust infrastructure",
    "客户转换": "customer conversion",
    "交易放大器：资产升级": "Transaction Amplifier: Asset Upgrade",
    "资产升级到交易": "asset upgrade to transaction",
    "政策兑付门槛": "policy redemption threshold",
    "完成生命周期收费": "complete lifecycle monetization",
    "业务边界：做到": "Business boundary: provide",
    "，暂不做需要牌照的发行": ", not licensed issuance for now",
    "亿吨滞压碳": "100M tons of stranded carbon",
    "资产质量差） ": "low asset quality) ",
    "资产质量差）": "low asset quality)",
    "资格认证": "qualification",
    "发行": "issuance",
    "再融资": "refinancing",
    "生命周期内": "within lifecycle",
    "，每个交易事件都收“绿色证明": ', charge a "green proof',
    "验证费”": 'verification fee"',
    "难交易": "hard to trade",
    "难融资": "hard to finance",
    "扫描资产质量": "scan asset quality",
    "发掘缺口": "identify gaps",
    "年绿色金融": "annual green finance",
    "（验证绿色": "(verify green",
    "政策门槛": "policy threshold",
    "难通过": "hard to pass",
    "难获益": "hard to benefit",
    "补齐缺口": "close gaps",
    "映射法规标准": "map regulations and standards",
    "循环评估": "continuous assessment",
    "输出可签字包": "output signable package",
    "高质量碳资产": "high-quality carbon assets",
    "（提升": "(improve",
    "价格": "price",
    "销售率）": "sell-through)",
    "政策兑付": "policy redemption",
    "本金补助": "principal subsidy",
    "利率补助）": "interest subsidy)",
    "税抵 ": "tax credit ",
    "商业模式": "Business Model",
    "先赚护照和闸机钱": "Earn passport and gate fees first",
    "再扩成事件验证和分润": "then expand into event verification and revenue share",
    "收费跟着决策节点走，随嵌入程度逐层变厚 ": "Fees follow decision nodes and deepen as embedding increases ",
    "收费跟着决策节点走，随嵌入程度逐层变厚": "Fees follow decision nodes and deepen as embedding increases",
    "护照费": "passport fee",
    "（产出证明）": "(proof output)",
    "产出": "output",
    "产出    ": "output    ",
    "护照（证明包）": "passport (proof package)",
    "触发": "trigger",
    "触发    ": "trigger    ",
    "生成": "generate",
    "更新护照": "update passport",
    "支付": "payment",
    "支付    ": "payment    ",
    "单价": "unit price",
    "单价    ": "unit price    ",
    "按量": "usage-based",
    "闸机费": "gate fee",
    "（准入判断）": "(access decision)",
    "验证": "verification",
    "风险评分": "risk score",
    "交易验证费": "transaction verification fee",
    "事件验证记录": "event verification record",
    "转手": "transfer",
    "融资": "financing",
    "更新": "update",
    "触发方": "triggering party",
    "交易结果分润": "transaction outcome share",
    "利率": "interest rate",
    "额度": "credit limit",
    "溢价": "premium",
    "利差改善": "spread improvement",
    "获益方": "beneficiary",
    "咨询": "consulting",
    "家*": "firms*",
    "份": "copies",
    "月": "month",
    "品牌": "brands",
    "供应链*": "supply chain*",
    "万吨": "10K tons",
    "吨": "tons",
    "机构": "institutions",
    "备注：只计算主力收入": "Note: only core revenue is counted",
    "核心行业": "core industry",
    "知识图谱": "knowledge graph",
    "方法学自动化流程": "methodology automation workflows",
    "碳资产流程模型": "carbon asset process models",
    "基准产品模型": "baseline product models",
    "验证因子匹配": "verification factor matching",
    "碳资产验证": "carbon asset verification",
    "绿金验证": "green-finance verification",
    "备注：护照和闸机飞轮沉淀数据，构建绿色经济": "Note: passport and gate flywheels accumulate data to build a green-economy",
    "专属大模型": "domain foundation model",
    "遵循 GDPR 及数据主权法规；授权使用聚合/脱敏数据进行模型训练与校验": "Comply with GDPR and data-sovereignty rules; use authorized aggregated/anonymized data for model training and validation",
    "工程与技术壁垒": "engineering and technical moat",
    "（全球唯一交付审计级结果": "(globally unique in delivering audit-grade results",
    "跨越多场景）": "across multiple scenarios)",
    "成本随规模下降": "cost falls with scale",
    "击穿点": "breakthrough point",
    "成本与精度壁垒": "cost and precision moat",
    "（越用越准": "(more accurate with use",
    "越便宜）": "cheaper with scale)",
    "准协议壁垒": "quasi-protocol moat",
    "（写入验收流程难替换）": "(embedded in acceptance workflows; hard to replace)",
    "护照规模": "passport scale",
    "闸机准确": "gate accuracy",
    "验收流程": "acceptance workflow",
    "采信成本↓": "trust cost down",
    "采信数量": "trusted volume",
    "壁垒": "moat",
    "不只效率和成本，而是把采信能力写进流程": "Not just efficiency and cost: trust capability is embedded into workflows",
    "同行在优化计算": "Peers optimize calculation",
    "我们在重建采信：自审计式自动化": "We rebuild trust acceptance: self-auditing automation",
    "成本飞轮": "cost flywheel",
    "流程依赖": "workflow dependency",
    "商业化": "commercialization",
    "碳阻迹商业化": "Carbonstop commercialization",
    "外资中国区总经理": "China GM at a foreign enterprise",
    "碳阻迹": "Carbonstop",
    "铁山 ": "Iron Mountain ",
    "铁山": "Iron Mountain",
    "创始人": "Founder",
    "联创": "Co-founder",
    "产品 ": "Product ",
    "榜单产品经理": "ranked product manager",
    "瓦格宁根大学": "Wageningen University",
    "碳阻迹高级产品经理": "Senior Product Manager at Carbonstop",
    "数据工程": "data engineering",
    "北京航空航天大学": "Beihang University",
    "工程师": "engineer",
    "投资）": "investment)",
    "加州大学": "University of California",
    "年市场营销": "years in marketing",
    "市场": "market",
    "营销": "marketing",
    "全球青年可持续": "Global Youth Sustainable",
    "联盟（": "Alliance (",
    "亚洲创业博览会亚军": "Asia Entrepreneurship Expo runner-up",
    "飞利浦": "Philips",
    "万宝路": "Marlboro",
    "全球可持续负责人": "Global Sustainability Lead",
    "金融专家": "finance expert",
    "碳金融": "carbon finance",
    "可持续专家": "sustainability expert",
    "领域专家": "domain expert",
    "卡耐基梅隆大学": "Carnegie Mellon University",
    "（博士）": "(PhD)",
    "清华大学（本科）": "Tsinghua University (B.S.)",
    "科学家": "scientist",
    "认证专家": "certification expert",
    "南洋理工博士": "PhD, Nanyang Technological University",
    "专家": "expert",
    "中国矿业大学教授": "Professor, China University of Mining and Technology",
    "轮次": "round",
    "种子 ": "seed ",
    "种子": "seed",
    "金额": "amount",
    "使用": "use",
    "目标": "targets",
    "咨询公司": "consulting firms",
    "资产项目": "asset projects",
    "研发": "R&D",
    "运营": "operations",
    "团队和融资：碳": "Team and Financing: carbon",
    "商业化 专家": "commercialization experts",
    "具备构建": "has all key capabilities to build",
    "基础设施的所有关键能力": "infrastructure",
    "终局与生态：绿色经济里的": "Endgame and Ecosystem: in the green economy",
    "构建采信网络": "build a trust network",
    "从合规和资产": "start from compliance and assets",
    "起步": "as the entry",
    "进入买方": "enter buyers,",
    "监管流程": "regulatory workflows",
    "服务绿色经济的每一笔业务": "serve every transaction in the green economy",
    "个人数据": "personal data",
    "信用": "credit",
    "支付": "payment",
    "信用网络": "credit network",
    "路由": "routing",
    "结算": "settlement",
    "接受银行": "acquiring bank",
    "发行银行": "issuing bank",
    "企业数据": "enterprise data",
    "护照签发": "passport issuance",
    "护照验证": "passport verification",
    "订单": "orders",
    "金融": "finance",
    "监管": "regulators",
    "企业": "enterprise",
    "碳专家": "carbon experts",
    "护照网络": "passport network",
    "金融信用网络": "financial credit network",
    "绿色采信网络": "green trust network",
    "信用卡持卡人": "cardholder",
    "商户": "merchant",
    "未来提交方与验收方都会是": "In the future, submitters and acceptors will both be",
    "为": "for",
    "这些": "these",
    "自主交易提供基础设施，让": "autonomous transactions, enabling",
    "携带可验证护照进入市场": "to enter markets with verifiable passports",
    "通过准入": "pass access checks",
    "在融资与交易事件中自主运行": "and run autonomously in financing and transaction events",
    "AI护照编译": "AI passport compiling",
    "AI准入验证": "AI access verification",
    "碳": "carbon",
    "运行碳排评估": "run carbon-emissions assessment",
    "抵消": "offset",
    "自主交易": "autonomous transactions",
    "气候印信": "Climate Seal",
    "（北京）科技有限公司": "(Beijing) Technology Co., Ltd.",
}

T.update(
    {
        "用": "use",
        "合规是企业向品牌": "Compliance is enterprises proving greenness to brands",
        "在资产和金融端：欧洲银行系统里有": "On the asset and finance side: European banking systems have",
        "碳数据变资产": "turn carbon data into assets",
        "“提交方证明自己绿（我合格了），验收方决定是否接受并给激励（给订单": '"The submitter proves it is green (I qualify), and the acceptor decides whether to accept and provide incentives (orders',
        "。 简单来说，我们帮助企业、产品、金融": "In simple terms, we help enterprises, products, and financial",
        "万不等。而验收方（大品牌海关": "tens of thousands to hundreds of thousands. Acceptors (large brands, customs",
        "万亿欧元的待认定绿色资产，但最终拿到认定、放出贷款或债券的只有": "trillion euros of green assets pending recognition, but only a small share ultimately receive recognition and unlock loans or bonds",
        "万亿美金、服务费超": "trillion USD, with service fees exceeding",
        "万到": "tens of thousands to",
        "万家企业、": "tens of thousands of enterprises,",
        "万美金，到": "USD 10K, to",
        "两边跑的是同一个": "both sides run on the same",
        "个大关卡、近百个决策岔口。以前全靠专家手工导航、数据操作、手动审计，走一步停一下，很多错误漏洞，数据是半黑盒。 现在的做法是，系统里跑两条数据流：第一条，": "major checkpoints and nearly one hundred decision forks. Previously this relied entirely on experts for manual navigation, data operation, and audit; each step paused, errors were common, and data was semi-black-box. Now the system runs two data streams: first,",
        "个小时的极限时间内产出，通过法国": "within an extreme turnaround of hours, passing the French",
        "个暴涨到": "surges to",
        "个月交付": "months to deliver",
        "个月内上线。我们已经锁定了中车和北汽集团这样的超级资产买方，并同步锁定了十多家资产开发公司、以及": "months. We have locked in major asset buyers such as CRRC and BAIC Group, and also more than a dozen asset-development firms plus",
        "个月，花": "months, costing",
        "个粪污处理项目和": "manure-treatment projects and",
        "个，计划覆盖": "projects; we plan to cover",
        "为什么采信这么难，有两个核心原因：": "Why is trusted acceptance so hard? There are two core reasons:",
        "也就是碳领域的": "that is, in the carbon domain,",
        "交易额和": "transaction volume and",
        "产生": "generated",
        "亿吨库存，每年还在新增几十亿吨，但真正卖出去流通的也只有": "100M tons of inventory, with billions of tons added every year, but only a small share is actually sold and circulated",
        "亿吨挤压在库存中的碳资产都是合规的，但是买方采购时有其他要求，这个口径差异导致不能成交； 高成本加口径差异，产生很重的“采信摩擦”，把大量本来合格的资产，拦在交易池外面。": "100M tons of carbon assets sitting in inventory are compliant, but buyers have additional procurement requirements. This criteria gap prevents transactions. High cost plus criteria gaps create heavy trust friction, keeping many otherwise qualified assets outside the trading pool.",
        "亿批次产品要做碳合规，每年花在咨询": "100M product batches need carbon compliance, and annual spend on consulting",
        "亿美元的跨越路线": "USD 100M scale-up path",
        "亿美金": "USD 100M",
        "亿美金，在我们眼里这是一个统一市场": "USD 100M in service fees. In our view, this is one unified market",
        "亿美金，而且还在涨。 所以，这个市场的瓶颈不是缺钱，而是“绿色属性的证明和验收”太难且太贵。就像这个沙漏：买家和银行害怕“漂绿”的风险，只敢挑那一小部分能被证明可信的资产。高可信的碳资产": "USD 100M and still rising. So the bottleneck is not lack of money, but that proving and accepting green attributes is too hard and expensive. Like this hourglass, buyers and banks fear greenwashing risk and only choose the small portion that can be proven trustworthy. High-trust carbon assets",
        "今天的绿色市场不缺资金，也不缺资产供给，但现状是：": "Today's green market does not lack capital or asset supply, but the current situation is:",
        "以上溢价，也说明了这个问题。": "premium, which also proves the point.",
        "传统一次绿色交易只收一次证明和验证费用，产生转手和交易这个费用不确定付给哪个服务商。但在": "A traditional green transaction only charges proof and verification once; when transfer and trading occur, it is unclear which service provider receives the fee. But under the",
        "像坐在副驾上的审计，同步做预审和风险评估，出现风险随时纠偏、并记录关键操作。 “边驾驶边监督”的双轨合并，形成横跨提交方和验证方的可信数据流，把半黑盒变成了高精度、透明的白盒，结果是：效率由月飙到小时；纯手工变全自动；风险全程可追溯；一次性抹平双方口径差异。": "like an auditor in the passenger seat, simultaneously pre-auditing and assessing risk, correcting issues in real time and recording key operations. This dual track of driving while supervising creates a trusted data flow across submitter and verifier, turning a semi-black-box into a high-precision transparent white box. The result: months become hours; manual work becomes automated; risk is traceable end to end; criteria gaps are resolved once.",
        "光伏资产，随时准备进场。": "PV assets, ready to enter at any time.",
        "减税等）。”": "tax reductions, etc.).\"",
        "几万到几十万美金的流程压到小时级和": "processes costing tens of thousands to hundreds of thousands of USD down to hours and",
        "分润": "revenue share",
        "到": "to",
        "可跨境": "cross-border",
        "各位好，我是气候印信的马旭光。气候印信致力于成为绿色经济里的": "Hello everyone, I am Max Ma from Climate Seal. Climate Seal is committed to becoming the green economy's",
        "合规客户想开发资产，资产客户要贷款，贷款客户要做资产和合规，三类客户互相转化、投喂数据，形成营收和数据飞轮": "Compliance clients want to develop assets, asset clients need loans, and loan clients need assets and compliance. The three client groups convert into one another and feed data into a revenue and data flywheel.",
        "合规工具给咨询公司，帮他们产能从": "compliance tools to consulting firms, helping their capacity move from",
        "同时": "At the same time",
        "围绕“提交方证明绿色、验收方验证绿色”这个本质，我们打造了：一套引擎，两种标准件的解决方案；": "Around the essence of submitters proving green and acceptors verifying green, we built a solution with one engine and two standard modules:",
        "国渠道。": "country channels.",
        "在业内最复杂的": "In the industry's most complex",
        "多个资产流程模型。": "asset process models.",
        "大客户": "major customers",
        "套自动化方法学、": "automated methodologies,",
        "审计上的费用超过": "and audit exceeds",
        "家咨询公司，赚取现金流和合规数据；会把三方审计前置到合规流程中，结果一次性合规；": "consulting firms, earning cash flow and compliance data; we will front-load third-party audit into the compliance process so the result is compliant in one pass;",
        "家客户、": "clients,",
        "小时交付审计级结果的产品，目前全球我们还没看到，我们做了苦行僧工作：沉淀了": "hours. We have not seen another product globally that can deliver audit-grade results this fast. We did the hard work and accumulated",
        "左右。": "or so.",
        "已完成，预计": "has been completed and is expected",
        "帮提交方构建“护照”：": "Build a passport for submitters:",
        "帮验收方构建“闸机”：": "Build a gate for acceptors:",
        "年的生命周期中，上架、转手、融资，都会重新护照和闸机，每一次验证，都收一次钱。": "year lifecycle, listing, transfer, and financing all trigger passport and gate verification again, and each verification is charged.",
        "年覆盖百家机构": "covering hundreds of institutions in the year",
        "开发资产": "develop assets",
        "引擎。不仅把过去几个月": "engine. It not only compresses what used to take months",
        "引擎在": "engine in",
        "必维）最高等级（": "Bureau Veritas) highest level (",
        "快速交易，能极大方便资产流转。我们的边界：只做“": "fast transactions, greatly facilitating asset circulation. Our boundary is to provide only",
        "我们理解碳中和的本质就是为了中和这个目标前进，一拨人执行减排，另一拨人去检查，检查过了就给税收减免、订单或低息贷款做激励。 所以无论是碳合规、碳资产，还是绿色贷款，本质都是同一件事：": "We understand carbon neutrality as moving toward the goal of neutralization: one group executes emissions reductions, another checks the result, and once checked, incentives such as tax reductions, orders, or low-interest loans are granted. So carbon compliance, carbon assets, and green loans are essentially the same thing:",
        "我们的护城河三层：": "Our moat has three layers:",
        "我们的收费跟着最重要的决策节点走，分三块：": "Our fees follow the most important decision nodes and are divided into three parts:",
        "我们的策略非常聚焦：从“护照”突破到“闸机”，最终占住验收和准入的裁判位。分三段推进：": "Our strategy is highly focused: break through with the passport, move into the gate, and ultimately occupy the judge position in acceptance and access. We advance in three phases:",
        "我们解决这个复杂问题的关键是构建这个底层技术：": "The key to solving this complex problem is building this core technology:",
        "批次的生成费”，频次跟法规走": "per-batch generation fee, with frequency driven by regulation",
        "承担增量。美国的": "drives incremental growth. The U.S.",
        "把复杂的准入规则、风险评估、状态确认系统化，护照一刷就判断能不能通过，解决“低成本验收问题”。": "systematize complex access rules, risk assessment, and status confirmation. Swipe the passport and the gate decides whether it passes, solving low-cost acceptance.",
        "按准入资产规模": "by admitted asset size",
        "按复杂度": "by complexity",
        "提交方做出合规证明，但验收方在合规基础上有额外验收标准。两头口径一对不上，比如：": "Submitters produce compliance proof, but acceptors have additional acceptance standards on top of compliance. If the two sides' criteria do not match, for example:",
        "提交方（合规企业": "Submitters (compliance enterprises",
        "提效而是交付审计级结果，能": "efficiency boost but delivery of audit-grade results; being able to",
        "整个战略中，": "Across the whole strategy,",
        "整合数据、做方法学对齐和证据链编排，产出可复用的绿色证明，解决低成本的证明问题。": "integrate data, align methodologies, orchestrate the evidence chain, and output reusable green proof, solving the low-cost proof problem.",
        "是重要的营收和交易频次放大器，": "is an important amplifier of revenue and transaction frequency,",
        "更重要的是，": "More importantly,",
        "构建的资产挖掘机替代手工开发，并且把资产风险评估模型和买方的要求前置到开发过程，提高开发质量，从原来用铲子挖金矿，现在用机器挖；": "asset miner replaces manual development and front-loads asset risk assessment models and buyer requirements into development, improving quality. It moves from mining gold with a shovel to mining with a machine;",
        "模式下，护照嵌入在资产里。在资产": "model, the passport is embedded in the asset. During the asset's",
        "次数收费”。": "per-call fee.",
        "海关证明绿色方换订单": "customs to prove greenness in exchange for orders",
        "生成护照，收“基础费”": "generate passports, charging a base fee",
        "的成本，更从根源上消除了买卖双方口径不一的问题，这套方案可以同时覆盖合规": "cost, and more fundamentally eliminates the mismatch between buyers' and sellers' criteria. This solution can cover compliance",
        "的技术开发和查验，不碰持牌发行，主要战场是海外客户；": "technical development and inspection; we do not touch licensed issuance, and our main battlefield is overseas customers;",
        "的溢价，证明高质量资产是硬通货。我们用": "premium, proving high-quality assets are hard currency. We use",
        "真正能被采信和流通的绿色资产，只有": "green assets that can truly be trusted and circulated account for only",
        "碳足迹合规中，自审计式自动化": "carbon footprint compliance, the self-auditing automation",
        "税收；碳资产是资产开发方向买方证明绿色换交易；绿金是贷款方向银行证明绿色换利率": "tax benefits; carbon assets are asset developers proving green to buyers in exchange for transactions; green finance is borrowers proving green to banks in exchange for rates",
        "第一块，提交方护照费": "First: submitter passport fee",
        "第一层，做得准": "Layer one: accuracy",
        "第一段：碳合规切入，做现金流。合规是已有的刚需，我们把高精度": "Phase one: enter through carbon compliance and build cash flow. Compliance is an existing must-have; we provide high-precision",
        "第一：证明和验证太贵、太慢；": "First: proof and verification are too expensive and too slow;",
        "第三块，交易验证费": "Third: transaction verification fee",
        "第三层，越用越难替换": "Layer three: harder to replace with use",
        "第三段：绿色金融，做利润池。用": "Phase three: green finance as the profit pool. Use",
        "第二块，验收方闸机费": "Second: acceptor gate fee",
        "第二层，越用越便宜": "Layer two: cheaper with use",
        "第二段：高质量碳资产": "Phase two: high-quality carbon assets",
        "第二：证明和验证口径不一致；": "Second: proof and verification criteria are inconsistent;",
        "等新投资者，拓宽销售范围。同时可拆分": "and other new investors, expanding the sales range. It can also be split",
        "类似自动驾驶一样，按方法学自动导航数据经过岔口，同时进行数据操作；第二条流，": "like autonomous driving, automatically navigating data through forks according to methodologies while performing data operations; the second stream,",
        "组件": "module",
        "置信度）的核验。成本降": "confidence) verification. Cost decreased",
        "能吸引碳圈外": "can attract non-carbon-circle",
        "能拿到": "can receive",
        "自监督自动驾驶）。": "self-supervised autonomous driving).",
        "贷款。底层逻辑完全共通，这是总规模超": "loans. The underlying logic is entirely shared; this is a market exceeding",
        "贷款方）要证明自己绿，得对齐方法学、梳理证据链、产出证明，要": "borrowers) must prove they are green by aligning methodologies, organizing evidence chains, and producing proof, which takes",
        "贷款用": "loan use",
        "贷款要过": "loans must pass",
        "资产侧：碳资产和": "On the asset side: carbon assets and",
        "资产，证明自己“到底是不是绿色的”，并且让这份绿色能被市场和监管接受，从而顺利完成出口、合规、资产交易和融资。": "assets prove whether they are truly green, and make that green status accepted by markets and regulators so export, compliance, asset transactions, and financing can proceed smoothly.",
        "采信基础设施": "trust infrastructure",
        "金融场景；": "finance scenarios;",
        "金融工具，把绿色金融的风控要求前置到开发阶段，帮企业拿更优的利率和额度，帮银行低成本做尽调风控，并考虑把贷款合同转换成": "financial tools to front-load green-finance risk-control requirements into the development stage, help enterprises obtain better rates and limits, help banks conduct low-cost due diligence and risk control, and consider converting loan contracts into",
        "银行的验收风控调用，收“基础费”": "banks' acceptance risk-control calls, charging a base fee",
        "银行）验证也很痛苦，靠手工尽调做风险评估和状态确认，成本几万到数百万。": "banks) also find verification painful, relying on manual due diligence for risk assessment and status confirmation, costing from tens of thousands to millions.",
        "验证因子，": "verification factors,",
        "，周期从月级压到小时级。目前": ", with cycle time compressed from months to hours. Currently",
        "，规模一旦拉满还会持续下降，会对传统手工咨询产生清场效应。": ", and once scale ramps, it will continue to fall, creating a clearing effect on traditional manual consulting.",
        "，说明大量资产在“采信”这关被毙掉了。合规端：每年有": ", showing that many assets are killed at the trust-acceptance gate. On the compliance side, every year",
        "：不是": ": not",
        "：企业合规": ": enterprise compliance",
        "：护照越多闸机越准，成本越低，原来无法负担成本的长尾客户会进来，形成飞轮。大买家越发依赖我们的风控，最终彻底写进验收流程，把提交方和验证方死死锁在一起，极难替换。": ": the more passports, the more accurate the gate; the lower the cost, the more long-tail customers can enter, forming a flywheel. Large buyers increasingly depend on our risk control, which eventually becomes written into acceptance workflows and tightly binds submitters and verifiers, making replacement extremely difficult.",
        "：海关": ": customs",
        "：现在能做到市场成本": ": we can already reach market cost",
        "：资产每次交易流转带来的证调用收费；如果我们能保证资产和贷款的质量，还能拿到资产交易和贷款利率的分润。 验证嵌得越深利润越厚。这支撑了从": ": fees from certificate calls each time an asset trades or circulates; if we can guarantee asset and loan quality, we can also receive revenue share from asset transactions and loan interest-rate improvements. The deeper verification is embedded, the thicker the margin. This supports a path from",
        "；自愿碳市场里挤压": "; the voluntary carbon market has accumulated",
        "单击此处编辑母版文本样式": "Click to edit Master text styles",
        "单击此处编辑母版标题样式": "Click to edit Master title style",
        "单击此处编辑母版副标题样式": "Click to edit Master subtitle style",
        "二级": "Second level",
        "三级": "Third level",
        "四级": "Fourth level",
        "五级": "Fifth level",
    }
)


def translate_text(text: str) -> str:
    if not re.search(r"[\u4e00-\u9fff]", text):
        return text
    leading = re.match(r"^\s*", text).group(0)
    trailing = re.search(r"\s*$", text).group(0)
    core = text.strip()
    if core in T:
        return leading + T[core] + trailing
    return text


def main() -> int:
    if not SRC.exists():
        print(f"Source not found: {SRC}", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td) / "deck.pptx"
        shutil.copyfile(SRC, tmp)
        with zipfile.ZipFile(tmp, "r") as zin:
            infos = zin.infolist()
            data = {info.filename: zin.read(info.filename) for info in infos}

        translated = 0
        untranslated: dict[str, int] = {}
        target_re = re.compile(r"ppt/(slides|notesSlides|slideLayouts|slideMasters|notesMasters)/.*\.xml$")

        for name, raw in list(data.items()):
            if not target_re.match(name):
                continue
            try:
                root = ET.fromstring(raw)
            except ET.ParseError:
                continue
            changed = False
            for node in root.findall(f".//{{{NS_A}}}t"):
                old = node.text or ""
                new = translate_text(old)
                if new != old:
                    node.text = new
                    translated += 1
                    changed = True
                elif re.search(r"[\u4e00-\u9fff]", old):
                    untranslated[old] = untranslated.get(old, 0) + 1
            if changed:
                data[name] = ET.tostring(root, encoding="utf-8", xml_declaration=True)

        with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as zout:
            for info in infos:
                zi = zipfile.ZipInfo(info.filename, info.date_time)
                zi.compress_type = zipfile.ZIP_DEFLATED
                zi.comment = info.comment
                zi.extra = info.extra
                zi.internal_attr = info.internal_attr
                zi.external_attr = info.external_attr
                zi.create_system = info.create_system
                zout.writestr(zi, data[info.filename])

    print(f"Wrote {OUT}")
    print(f"Translated text runs: {translated}")
    if untranslated:
        print("Untranslated Chinese text runs:")
        for key, count in sorted(untranslated.items(), key=lambda kv: (-kv[1], kv[0])):
            print(f"{count}\t{key}")
    return 0 if not untranslated else 2


if __name__ == "__main__":
    raise SystemExit(main())
